services:
  - type: static
    name: site-raffiner
    plan: free
    buildCommand: npm ci && npm run build:static
    staticPublishPath: ./build/client
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
